server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sixthsense
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

jwt:
  issuer: sixsense@gmail.com
  secret-key: sixsense-newsfeed

logging:
  level:
    org.hibernate.type.descriptor.sql: info

#깃 이그노어에 추가 안되는거 같은데 어떻게 하는지.....